"""modificate cabinets

Revision ID: 01b40a28edbd
Revises: 6cfcca5146f0
Create Date: 2026-05-11 13:16:56.302349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01b40a28edbd'
down_revision: Union[str, None] = '6cfcca5146f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cabinets', sa.Column('purpose', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_cabinets_type'), 'cabinets', ['type'], unique=False)
    op.create_index(op.f('ix_cabinets_warranty_ends_at'), 'cabinets', ['warranty_ends_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cabinets_warranty_ends_at'), table_name='cabinets')
    op.drop_index(op.f('ix_cabinets_type'), table_name='cabinets')
    op.drop_column('cabinets', 'purpose')
    # ### end Alembic commands ###
