"""make kb article content nullable

Revision ID: 169b1140b504
Revises: 72620ad92d5a
Create Date: 2026-05-18 06:47:41.547825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '169b1140b504'
down_revision: Union[str, None] = '72620ad92d5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kb_articles', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('kb_articles', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
