"""make cabinet_id nullable id documents photos requests

Revision ID: 1b5df7789817
Revises: 01b40a28edbd
Create Date: 2026-05-15 05:37:15.021317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b5df7789817'
down_revision: Union[str, None] = '01b40a28edbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cabinet_photos', 'cabinet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('document_requests', 'cabinet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('documents', 'cabinet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'cabinet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('document_requests', 'cabinet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('cabinet_photos', 'cabinet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
