"""add actor_role to audit_logs, warranty_notiF_log

Revision ID: 6a5a3918aa88
Revises: f147aee193aa
Create Date: 2026-05-19 14:30:59.476760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a5a3918aa88'
down_revision: Union[str, None] = 'f147aee193aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('actor_role', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_audit_logs_actor_role'), 'audit_logs', ['actor_role'], unique=False)
    op.drop_constraint('audit_logs_actor_id_fkey', 'audit_logs', type_='foreignkey')
    op.create_foreign_key(None, 'audit_logs', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.create_foreign_key('audit_logs_actor_id_fkey', 'audit_logs', 'users', ['actor_id'], ['id'])
    op.drop_index(op.f('ix_audit_logs_actor_role'), table_name='audit_logs')
    op.drop_column('audit_logs', 'actor_role')
    # ### end Alembic commands ###
