"""add full schema

Revision ID: 6af42b08ea04
Revises: 18b609dc9120
Create Date: 2026-05-08 13:15:54.093608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6af42b08ea04'
down_revision: Union[str, None] = '18b609dc9120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unique_code', sa.String(length=100), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('object_number', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('warranty_starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('warranty_ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('admin_internal_name', sa.String(length=200), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cabinets_unique_code'), 'cabinets', ['unique_code'], unique=True)
    op.create_table('faq_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['faq_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_categories_parent_id'), 'faq_categories', ['parent_id'], unique=False)
    op.create_table('kb_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['kb_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_kb_categories_parent_id'), 'kb_categories', ['parent_id'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=True)
    op.create_table('cabinet_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cabinet_photos_cabinet_id'), 'cabinet_photos', ['cabinet_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_cabinet_id'), 'documents', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_documents_doc_type'), 'documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_documents_requires_approval'), 'documents', ['requires_approval'], unique=False)
    op.create_table('faq_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['faq_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_entries_category_id'), 'faq_entries', ['category_id'], unique=False)
    op.create_index(op.f('ix_faq_entries_is_published'), 'faq_entries', ['is_published'], unique=False)
    op.create_table('kb_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['kb_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index(op.f('ix_kb_articles_category_id'), 'kb_articles', ['category_id'], unique=False)
    op.create_index(op.f('ix_kb_articles_is_published'), 'kb_articles', ['is_published'], unique=False)
    op.create_index(op.f('ix_kb_articles_title'), 'kb_articles', ['title'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('cabinet_addition_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.String(length=500), nullable=False),
    sa.Column('user_comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('resolved_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cabinet_addition_requests_cabinet_id'), 'cabinet_addition_requests', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_cabinet_addition_requests_resolved_by_admin_id'), 'cabinet_addition_requests', ['resolved_by_admin_id'], unique=False)
    op.create_index(op.f('ix_cabinet_addition_requests_status'), 'cabinet_addition_requests', ['status'], unique=False)
    op.create_index(op.f('ix_cabinet_addition_requests_user_id'), 'cabinet_addition_requests', ['user_id'], unique=False)
    op.create_table('cabinet_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('block_type', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("block_type IN ('blacklist', 'whitelist')", name='ck_cabinet_block_type'),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cabinet_id', name='uq_cabinet_block_user_cabinet')
    )
    op.create_index(op.f('ix_cabinet_blocks_cabinet_id'), 'cabinet_blocks', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_cabinet_blocks_user_id'), 'cabinet_blocks', ['user_id'], unique=False)
    op.create_table('cabinet_share_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('user_comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('resolved_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cabinet_share_requests_cabinet_id'), 'cabinet_share_requests', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_cabinet_share_requests_resolved_by_admin_id'), 'cabinet_share_requests', ['resolved_by_admin_id'], unique=False)
    op.create_index(op.f('ix_cabinet_share_requests_status'), 'cabinet_share_requests', ['status'], unique=False)
    op.create_index(op.f('ix_cabinet_share_requests_user_id'), 'cabinet_share_requests', ['user_id'], unique=False)
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_type', sa.String(length=20), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cabinet_id', name='uq_user_cabinet_chat')
    )
    op.create_index(op.f('ix_chats_cabinet_id'), 'chats', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_chats_chat_type'), 'chats', ['chat_type'], unique=False)
    op.create_index(op.f('ix_chats_last_message_at'), 'chats', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_chats_user_id'), 'chats', ['user_id'], unique=False)
    op.create_table('device_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("platform IN ('ios', 'android')", name='ck_device_token_platform'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_device_tokens_platform'), 'device_tokens', ['platform'], unique=False)
    op.create_index(op.f('ix_device_tokens_user_id'), 'device_tokens', ['user_id'], unique=False)
    op.create_table('document_access',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('granted_by_admin_id', sa.Integer(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['granted_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'document_id')
    )
    op.create_table('document_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('resolved_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_requests_cabinet_id'), 'document_requests', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_document_requests_document_id'), 'document_requests', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_requests_status'), 'document_requests', ['status'], unique=False)
    op.create_index(op.f('ix_document_requests_user_id'), 'document_requests', ['user_id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_messages', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('promotional', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('warranty_expiring', sa.Boolean(), server_default='true', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_cabinet_id'), 'service_requests', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_service_requests_request_type'), 'service_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_service_requests_status'), 'service_requests', ['status'], unique=False)
    op.create_index(op.f('ix_service_requests_user_id'), 'service_requests', ['user_id'], unique=False)
    op.create_table('user_cabinets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('custom_name', sa.String(length=200), nullable=True),
    sa.Column('custom_comment', sa.Text(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'cabinet_id', name='uq_user_cabinet')
    )
    op.create_index(op.f('ix_user_cabinets_cabinet_id'), 'user_cabinets', ['cabinet_id'], unique=False)
    op.create_index(op.f('ix_user_cabinets_user_id'), 'user_cabinets', ['user_id'], unique=False)
    op.create_index('uq_user_cabinet_primary', 'user_cabinets', ['cabinet_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('reply_to_message_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_chat_created', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_chat_id'), 'messages', ['chat_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_is_read'), 'messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_messages_reply_to_message_id'), 'messages', ['reply_to_message_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('message_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('attachment_type', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_attachments_attachment_type'), 'message_attachments', ['attachment_type'], unique=False)
    op.create_index(op.f('ix_message_attachments_message_id'), 'message_attachments', ['message_id'], unique=False)
    op.create_table('message_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'user_id', 'emoji', name='uq_message_reaction')
    )
    op.create_index(op.f('ix_message_reactions_message_id'), 'message_reactions', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_reactions_user_id'), 'message_reactions', ['user_id'], unique=False)
    op.add_column('roles', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('login', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('user_type', sa.String(length=20), nullable=True, comment='Значения: individual or organization'))
    op.add_column('users', sa.Column('organization_name', sa.String(length=255), nullable=True))
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.alter_column('users', 'phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('users', 'organization_name')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'login')
    op.drop_column('roles', 'description')
    op.drop_index(op.f('ix_message_reactions_user_id'), table_name='message_reactions')
    op.drop_index(op.f('ix_message_reactions_message_id'), table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index(op.f('ix_message_attachments_message_id'), table_name='message_attachments')
    op.drop_index(op.f('ix_message_attachments_attachment_type'), table_name='message_attachments')
    op.drop_table('message_attachments')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_reply_to_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_is_read'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_id'), table_name='messages')
    op.drop_index('ix_messages_chat_created', table_name='messages')
    op.drop_table('messages')
    op.drop_index('uq_user_cabinet_primary', table_name='user_cabinets', postgresql_where=sa.text('is_primary = true'))
    op.drop_index(op.f('ix_user_cabinets_user_id'), table_name='user_cabinets')
    op.drop_index(op.f('ix_user_cabinets_cabinet_id'), table_name='user_cabinets')
    op.drop_table('user_cabinets')
    op.drop_index(op.f('ix_service_requests_user_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_status'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_request_type'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_cabinet_id'), table_name='service_requests')
    op.drop_table('service_requests')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_document_requests_user_id'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_status'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_document_id'), table_name='document_requests')
    op.drop_index(op.f('ix_document_requests_cabinet_id'), table_name='document_requests')
    op.drop_table('document_requests')
    op.drop_table('document_access')
    op.drop_index(op.f('ix_device_tokens_user_id'), table_name='device_tokens')
    op.drop_index(op.f('ix_device_tokens_platform'), table_name='device_tokens')
    op.drop_table('device_tokens')
    op.drop_index(op.f('ix_chats_user_id'), table_name='chats')
    op.drop_index(op.f('ix_chats_last_message_at'), table_name='chats')
    op.drop_index(op.f('ix_chats_chat_type'), table_name='chats')
    op.drop_index(op.f('ix_chats_cabinet_id'), table_name='chats')
    op.drop_table('chats')
    op.drop_index(op.f('ix_cabinet_share_requests_user_id'), table_name='cabinet_share_requests')
    op.drop_index(op.f('ix_cabinet_share_requests_status'), table_name='cabinet_share_requests')
    op.drop_index(op.f('ix_cabinet_share_requests_resolved_by_admin_id'), table_name='cabinet_share_requests')
    op.drop_index(op.f('ix_cabinet_share_requests_cabinet_id'), table_name='cabinet_share_requests')
    op.drop_table('cabinet_share_requests')
    op.drop_index(op.f('ix_cabinet_blocks_user_id'), table_name='cabinet_blocks')
    op.drop_index(op.f('ix_cabinet_blocks_cabinet_id'), table_name='cabinet_blocks')
    op.drop_table('cabinet_blocks')
    op.drop_index(op.f('ix_cabinet_addition_requests_user_id'), table_name='cabinet_addition_requests')
    op.drop_index(op.f('ix_cabinet_addition_requests_status'), table_name='cabinet_addition_requests')
    op.drop_index(op.f('ix_cabinet_addition_requests_resolved_by_admin_id'), table_name='cabinet_addition_requests')
    op.drop_index(op.f('ix_cabinet_addition_requests_cabinet_id'), table_name='cabinet_addition_requests')
    op.drop_table('cabinet_addition_requests')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_kb_articles_title'), table_name='kb_articles')
    op.drop_index(op.f('ix_kb_articles_is_published'), table_name='kb_articles')
    op.drop_index(op.f('ix_kb_articles_category_id'), table_name='kb_articles')
    op.drop_table('kb_articles')
    op.drop_index(op.f('ix_faq_entries_is_published'), table_name='faq_entries')
    op.drop_index(op.f('ix_faq_entries_category_id'), table_name='faq_entries')
    op.drop_table('faq_entries')
    op.drop_index(op.f('ix_documents_requires_approval'), table_name='documents')
    op.drop_index(op.f('ix_documents_doc_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_cabinet_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_cabinet_photos_cabinet_id'), table_name='cabinet_photos')
    op.drop_table('cabinet_photos')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_kb_categories_parent_id'), table_name='kb_categories')
    op.drop_table('kb_categories')
    op.drop_index(op.f('ix_faq_categories_parent_id'), table_name='faq_categories')
    op.drop_table('faq_categories')
    op.drop_index(op.f('ix_cabinets_unique_code'), table_name='cabinets')
    op.drop_table('cabinets')
    # ### end Alembic commands ###
