"""update char model bot fields

Revision ID: 72620ad92d5a
Revises: dd95d98d3c44
Create Date: 2026-05-15 09:38:25.683498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72620ad92d5a'
down_revision: Union[str, None] = 'dd95d98d3c44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('bot_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('chats', sa.Column('operator_requested', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chats', sa.Column('bot_no_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('chats', sa.Column('problem_status', sa.String(length=20), server_default='open', nullable=False))
    op.add_column('chats', sa.Column('follow_up_sent', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('chats', sa.Column('last_user_message_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint('uq_user_cabinet_chat', 'chats', type_='unique')
    op.create_index('uq_user_cabinet_chat', 'chats', ['user_id', 'cabinet_id'], unique=True, postgresql_where=sa.text("chat_type = 'cabinet' AND cabinet_id IS NOT NULL"))
    op.create_index(op.f('ix_chats_problem_status'), 'chats', ['problem_status'], unique=False)
    op.create_index('uq_user_notes_chat', 'chats', ['user_id'], unique=True, postgresql_where=sa.text("chat_type = 'notes'"))
    op.create_index('uq_user_support_chat', 'chats', ['user_id'], unique=True, postgresql_where=sa.text("chat_type = 'support'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_user_support_chat', table_name='chats', postgresql_where=sa.text("chat_type = 'support'"))
    op.drop_index('uq_user_notes_chat', table_name='chats', postgresql_where=sa.text("chat_type = 'notes'"))
    op.drop_index(op.f('ix_chats_problem_status'), table_name='chats')
    op.drop_index('uq_user_cabinet_chat', table_name='chats', postgresql_where=sa.text("chat_type = 'cabinet' AND cabinet_id IS NOT NULL"))
    op.create_unique_constraint('uq_user_cabinet_chat', 'chats', ['user_id', 'cabinet_id'])
    op.drop_column('chats', 'last_user_message_at')
    op.drop_column('chats', 'follow_up_sent')
    op.drop_column('chats', 'problem_status')
    op.drop_column('chats', 'bot_no_count')
    op.drop_column('chats', 'operator_requested')
    op.drop_column('chats', 'bot_active')
    # ### end Alembic commands ###
