"""add tags favorites kb attachments

Revision ID: b3a274437d23
Revises: 1b5df7789817
Create Date: 2026-05-15 06:17:27.457790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3a274437d23'
down_revision: Union[str, None] = '1b5df7789817'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_tags',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', 'tag_id')
    )
    op.create_table('kb_article_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['kb_articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kb_article_attachments_article_id'), 'kb_article_attachments', ['article_id'], unique=False)
    op.create_index(op.f('ix_kb_article_attachments_doc_type'), 'kb_article_attachments', ['doc_type'], unique=False)
    op.create_index(op.f('ix_kb_article_attachments_requires_approval'), 'kb_article_attachments', ['requires_approval'], unique=False)
    op.create_table('kb_article_tags',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['kb_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('article_id', 'tag_id')
    )
    op.create_table('user_favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('document', 'kb_article')", name='ck_user_favorite_entity_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'entity_type', 'entity_id', name='uq_user_favorite')
    )
    op.create_index(op.f('ix_user_favorites_entity_id'), 'user_favorites', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_favorites_entity_type'), 'user_favorites', ['entity_type'], unique=False)
    op.create_index(op.f('ix_user_favorites_user_id'), 'user_favorites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_favorites_user_id'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_entity_type'), table_name='user_favorites')
    op.drop_index(op.f('ix_user_favorites_entity_id'), table_name='user_favorites')
    op.drop_table('user_favorites')
    op.drop_table('kb_article_tags')
    op.drop_index(op.f('ix_kb_article_attachments_requires_approval'), table_name='kb_article_attachments')
    op.drop_index(op.f('ix_kb_article_attachments_doc_type'), table_name='kb_article_attachments')
    op.drop_index(op.f('ix_kb_article_attachments_article_id'), table_name='kb_article_attachments')
    op.drop_table('kb_article_attachments')
    op.drop_table('document_tags')
    # ### end Alembic commands ###
