"""revert cabinet_id to not null

Revision ID: dd95d98d3c44
Revises: b3a274437d23
Create Date: 2026-05-15 08:04:01.033287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd95d98d3c44'
down_revision: Union[str, None] = 'b3a274437d23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cabinet_photos', 'cabinet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('document_requests', 'cabinet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('documents', 'cabinet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'cabinet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('document_requests', 'cabinet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('cabinet_photos', 'cabinet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
