"""add warranty_notif_log

Revision ID: f147aee193aa
Revises: 169b1140b504
Create Date: 2026-05-18 07:31:05.132017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f147aee193aa'
down_revision: Union[str, None] = '169b1140b504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warranty_notif_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('days_before', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cabinet_id', 'days_before', name='uq_warranty_notif_log')
    )
    op.create_index(op.f('ix_warranty_notif_log_cabinet_id'), 'warranty_notif_log', ['cabinet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_warranty_notif_log_cabinet_id'), table_name='warranty_notif_log')
    op.drop_table('warranty_notif_log')
    # ### end Alembic commands ###
